prompt title: §eTexture Packs
prompt on login: false
default texture pack: default
texturepacks:
  dokucraftlight:
    name: Dokucraft - Light
    url: http://dl.dropbox.com/u/27507830/TextureMe/DokuCraft%20-%20Light.zip
  dokucraftdark:
    name: Dokucraft - Dark
    url: http://dl.dropbox.com/u/27507830/TextureMe/DokuCraft%20-%20Dark.zip
  dokucrafthigh:
    name: Dokucraft - High
    url: http://dl.dropbox.com/u/27507830/TextureMe/DokuCraft%20-%20High.zip