name: TextureMe
version: "${project.version}"
description: Choose a texture pack!
author: Windwaker 
main: net.windwaker.textureme.TextureMe
database: false
softdepend: [Spout]
permissions:
  textureme.*:
    description: Gives access to all TextureMe commands
    children:
      textureme.select: true
      textureme.configure: true
      textureme.playerschoice: true
  textureme.select:
    description: Allows you to select a texture pack
    default: true
  textureme.configure:
    description: Allows you to configure TextureMe via the GUI
    default: false
  textureme.playerschoice:
    description: Allows player to choose to default to his old pack
    default: true